### ISSUE TITLE
Differentiate not found entry from not found guild or user in `fetch_ban`

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#209]
### Summary
Differentiate not found entry from not found guild or user in `fetch_ban`

### Problem
Unable to differentiate if the user is not found or if you just provided an unknown user/guild due to how discord implements this

### Ideal implementation
TBD

**Comment by nekokatt** [comment]
They probably have an error code for it, but until Discord decide to document the format they want to provide us errors in, I don't really want to implement stuff to check that, especially since the v6 format varies so much to the v7 one, and half the useful info on the v7/v8 one is under attributes starting with `_`, so I assume they are private detail that shouldn't be used.
